
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\dselm\OneDrive\Bureau\epsi_sn2\projet_transversal_python\EcoTrack\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    540.0,
    image=image_image_1
)

canvas.create_rectangle(
    957.9998790067912,
    121.0,
    959.9951171875,
    958.999982827052,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1084.0,
    192.0,
    1796.0,
    888.0,
    fill="#088A7A",
    outline="")

canvas.create_rectangle(
    1084.0,
    192.0,
    1796.0,
    888.0,
    fill="#088A7A",
    outline="")

canvas.create_text(
    1353.55859375,
    683.798828125,
    anchor="nw",
    text="Ou connectez-vous avec",
    fill="#FFFFFF",
    font=("Poppins Regular", 14 * -1)
)

canvas.create_text(
    1184.0,
    247.0,
    anchor="nw",
    text="Connexion",
    fill="#FFFFFF",
    font=("Poppins Regular", 38 * -1)
)

canvas.create_text(
    1294.90185546875,
    816.1318359375,
    anchor="nw",
    text="Pas encore de compte ?",
    fill="#FFFFFF",
    font=("Poppins Regular", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1470.0,
    y=807.0,
    width=131.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: truc.connexion(entry_1.get(),entry_2.get()),
    relief="flat"
)
button_2.place(
    x=1179.0,
    y=597.0,
    width=527.0,
    height=65.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1179.0,
    y=730.0,
    width=166.0,
    height=65.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1362.0,
    y=730.0,
    width=163.0,
    height=61.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=1541.0,
    y=730.0,
    width=165.0,
    height=61.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1441.0291748046875,
    389.95703125,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=1193.7626953125,
    y=363.9072265625,
    width=494.532958984375,
    height=50.099609375
)

canvas.create_text(
    1207.43115234375,
    379.537109375,
    anchor="nw",
    text="pseudo@gmail.com",
    fill="#BCBEC0",
    font=("Poppins Regular", 14 * -1)
)

canvas.create_text(
    1183.7626953125,
    333.689453125,
    anchor="nw",
    text="Email",
    fill="#FFFFFF",
    font=("Poppins Regular", 18 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1441.0291748046875,
    500.408203125,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=1193.7626953125,
    y=474.3583984375,
    width=494.532958984375,
    height=50.099609375
)

canvas.create_text(
    1207.43115234375,
    489.98828125,
    anchor="nw",
    text="Mot de passe",
    fill="#BCBEC0",
    font=("Poppins Regular", 14 * -1)
)

canvas.create_text(
    1183.7626953125,
    444.140625,
    anchor="nw",
    text="Mot de passe",
    fill="#FFFFFF",
    font=("Poppins Regular", 18 * -1)
)

canvas.create_text(
    1183.7626953125,
    542.087890625,
    anchor="nw",
    text="Mot de passe?",
    fill="#FFFFFF",
    font=("Poppins Regular", 12 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    494.0,
    535.0,
    image=image_image_2
)
window.resizable(True, True)



"""----------------------------------------------------------------------------------"""

from user import Users

truc=Users()



window.mainloop()